import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"
import type { Match, Team, Player, Inning } from "./types"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function generateScorecardHTML(match: Match, teams: Team[], players: Player[]) {
  const getTeamName = (id: string) => teams.find(t => t.id === id)?.name || 'Unknown';
  const getPlayerName = (id: string) => players.find(p => p.id === id)?.name || 'Unknown';

  const renderInning = (inning: Inning) => {
    const battingTeamName = getTeamName(inning.battingTeamId);
    return `
      <div class="inning">
        <h2>${battingTeamName} Innings</h2>
        <table>
          <thead>
            <tr>
              <th>Batsman</th>
              <th>R</th>
              <th>B</th>
              <th>4s</th>
              <th>6s</th>
              <th>SR</th>
            </tr>
          </thead>
          <tbody>
            ${players.filter(p => (match.team1PlayerIds?.includes(p.id) || match.team2PlayerIds?.includes(p.id)) && p.teamId === inning.battingTeamId).map(p => {
              const deliveries = inning.deliveryHistory.filter(d => d.strikerId === p.id);
              const runs = deliveries.reduce((acc, d) => acc + (d.extra !== 'byes' && d.extra !== 'legbyes' ? d.runs : 0), 0);
              const balls = deliveries.filter(d => d.extra !== 'wide').length;
              const fours = deliveries.filter(d => d.runs === 4 && !d.extra).length;
              const sixes = deliveries.filter(d => d.runs === 6 && !d.extra).length;
              const sr = balls > 0 ? ((runs / balls) * 100).toFixed(2) : '0.00';
              return `<tr><td>${p.name}</td><td>${runs}</td><td>${balls}</td><td>${fours}</td><td>${sixes}</td><td>${sr}</td></tr>`;
            }).join('')}
          </tbody>
        </table>
        <div class="total">Total: ${inning.score}/${inning.wickets} (${inning.overs.toFixed(1)} Overs)</div>
      </div>
    `;
  };

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Scorecard - ${getTeamName(match.team1Id)} vs ${getTeamName(match.team2Id)}</title>
      <style>
        body { font-family: sans-serif; padding: 20px; color: #333; }
        h1 { color: #2563eb; }
        .match-info { margin-bottom: 20px; border-bottom: 2px solid #eee; padding-bottom: 10px; }
        .inning { margin-bottom: 30px; border: 1px solid #ddd; border-radius: 8px; overflow: hidden; }
        .inning h2 { background: #f8fafc; margin: 0; padding: 10px 15px; border-bottom: 1px solid #ddd; font-size: 1.2em; }
        table { width: 100%; border-collapse: collapse; }
        th, td { text-align: left; padding: 10px 15px; border-bottom: 1px solid #eee; }
        th { background: #f1f5f9; font-size: 0.9em; text-transform: uppercase; color: #64748b; }
        .total { padding: 15px; background: #eff6ff; font-weight: bold; text-align: right; }
        .result { font-size: 1.5em; font-weight: bold; color: #059669; text-align: center; margin-top: 20px; }
      </style>
    </head>
    <body>
      <div class="match-info">
        <h1>${getTeamName(match.team1Id)} vs ${getTeamName(match.team2Id)}</h1>
        <p>${new Date(match.date).toLocaleDateString()} • ${match.overs} Over Match</p>
      </div>
      ${match.innings.map(renderInning).join('')}
      <div class="result">${match.result || 'Match in Progress'}</div>
      <footer style="margin-top: 40px; text-align: center; color: #94a3b8; font-size: 0.8em;">
        Generated by CricMates
      </footer>
    </body>
    </html>
  `;
}

export function downloadScorecard(match: Match, teams: Team[], players: Player[]) {
  const html = generateScorecardHTML(match, teams, players);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Scorecard_${Date.now()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
