'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Sparkles, Loader2, Award, ListChecks } from 'lucide-react';
import { generateMatchSummary, type MatchSummaryOutput } from '@/ai/flows/match-summary-flow';
import type { Match, Team, Player } from '@/lib/types';

interface MatchAISummaryProps {
  match: Match;
  teams: Team[];
  players: Player[];
}

export function MatchAISummary({ match, teams, players }: MatchAISummaryProps) {
  const [summary, setSummary] = useState<MatchSummaryOutput | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const team1 = teams.find(t => t.id === match.team1Id)?.name || 'Team 1';
      const team2 = teams.find(t => t.id === match.team2Id)?.name || 'Team 2';

      // Prepare a string representation of the scorecard
      const scorecardData = match.innings.map((inning, idx) => {
        const battingTeam = teams.find(t => t.id === inning.battingTeamId)?.name;
        const deliveries = inning.deliveryHistory.slice(0, 50).map(d => {
            const striker = players.find(p => p.id === d.strikerId)?.name;
            return `${striker}: ${d.outcome}`;
        }).join(', ');
        return `Inning ${idx + 1} (${battingTeam}): ${inning.score}/${inning.wickets} in ${inning.overs} overs. Top moments: ${deliveries}`;
      }).join('\n');

      const result = await generateMatchSummary({
        team1Name: team1,
        team2Name: team2,
        scorecardData,
        result: match.result,
      });
      setSummary(result);
    } catch (error) {
      console.error('Error generating summary:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  if (!summary && !isGenerating) {
    return (
      <Card className="border-dashed">
        <CardContent className="flex flex-col items-center justify-center py-12 text-center space-y-4">
          <div className="p-3 bg-primary/10 rounded-full">
            <Sparkles className="h-8 w-8 text-primary" />
          </div>
          <div className="space-y-2">
            <h3 className="text-xl font-bold">AI Match Insights</h3>
            <p className="text-muted-foreground max-w-xs">
              Let CricMates AI analyze the scorecard and generate a professional summary for this match.
            </p>
          </div>
          <Button onClick={handleGenerate} className="gap-2">
            <Sparkles className="h-4 w-4" /> Generate Summary
          </Button>
        </CardContent>
      </Card>
    );
  }

  if (isGenerating) {
    return (
      <Card className="animate-pulse">
        <CardContent className="flex flex-col items-center justify-center py-24 text-center space-y-4">
          <Loader2 className="h-8 w-8 text-primary animate-spin" />
          <p className="font-medium">AI is analyzing the deliveries...</p>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      <Card className="overflow-hidden border-primary/20 bg-primary/5">
        <CardHeader className="bg-primary/10">
          <CardTitle className="flex items-center gap-2">
            <Award className="h-5 w-5 text-primary" />
            The Verdict
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-6">
          <p className="text-xl font-bold italic text-primary">"{summary?.verdict}"</p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Match Report</CardTitle>
          <CardDescription>Generated by CricMates AI</CardDescription>
        </CardHeader>
        <CardContent className="prose prose-sm dark:prose-invert max-w-none">
          <p className="whitespace-pre-wrap leading-relaxed">{summary?.narrative}</p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ListChecks className="h-5 w-5 text-primary" />
            Key Moments
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="space-y-3">
            {summary?.keyMoments.map((moment, index) => (
              <li key={index} className="flex gap-3 text-sm">
                <span className="flex-none flex items-center justify-center h-5 w-5 rounded-full bg-primary/10 text-primary text-[10px] font-bold">
                  {index + 1}
                </span>
                {moment}
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>
      
      <div className="flex justify-center">
          <Button variant="ghost" size="sm" onClick={handleGenerate} className="text-muted-foreground">
              <Sparkles className="mr-2 h-3 w-3" /> Regenerate Summary
          </Button>
      </div>
    </div>
  );
}
